#  - platform: template
#    switches:
#      away_mode:
#        value_template: >
#                        {% if states.sensor.away_mode.state == 'off' %}
#                          off
#                        {% elif states.sensor.away_mode.state == 'on' %}
#                          on
#                        {% else %}
#                          off
#                        {% endif %}
#        turn_on:
#          service: homeassistant.turn_on
#          entity_id: script.sleep_mode_on
#        turn_off:
#          service: switch.turn_on
#          entity_id: switch.skylight_close

## EXAMPLE MQTT SWITCH

#  - platform : mqtt
#    name: "Andrew Ceiling Fan"
#    state_topic: "stat/sonoff_fan/POWER"
#    command_topic: "cmnd/sonoff_fan/POWER"
#    payload_on: "ON"
#    payload_off: "OFF"
#    optimistic: false
#    retain: true


## EXAMPLE MQTT SWITCH

    
#  - platform: template
#    switches:
#      arlo:
#        value_template: >
#                        {% if states.sensor.arlo_state.state == 'off' %}
#                          off
#                        {% else %}
#                          on
#                        {% endif %}
#        turn_on:
#          service: homeassistant.turn_on
#          entity_id: script.arlo_armed
#        turn_off:
#          service: homeassistant.turn_on
#          entity_id: script.arlo_disarmed