homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret long
  longitude: !secret lat
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 130
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Australia/Melbourne
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

recorder:
  purge_interval: 3
  purge_keep_days: 5

# Enables the frontend
frontend:

config:

#map:

http:
  # Uncomment this to add a password (recommended!)
   api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
   base_url: 192.168.87.15:812
   cors_allowed_origins:
    - http://192.168.87.15:7080
    
# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

logger:
  default: error
  logs:
    homeassistant.core: critical

# Track the sun
sun:

#XIAOMI
xiaomi_aqara:
 gateways:
   - mac:
     key: !secret xiaomi_key
  
# mqtt:
  # broker: 127.0.0.1
  # port: 1883
  # client_id: home-assistant-1
  # username: !secret mqtt_user
  # password: !secret mqtt_pass
  
## Google Cast
#media_player:
## ChromeCast Main TV
#  - platform: cast
#    host: 192.168.87.34
## ChromeCast Bedroom
#  - platform: cast
#    host: 192.168.1.12
## Google Home    
#  - platform: cast
#    host: 192.168.1.10
    
## Chromecast Audio Whole House    
#  - platform: cast
#    host: 192.168.1.5
  
# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

#duckdns:
 # domain: !secret duckdns_user
  #access_token: !secret duckdns_tok
 
light:
  - platform: yeelight
    devices:
      192.168.87.56:
        name: Family Room Lamp
        transition: 1000
        use_music_mode: True
  - platform: flux_led
    devices:
      192.168.87.243:
        name: led_strip

  
#CAMERAS  
##    
  
##ANDROID
# android_ip_webcam:
  # - host: 192.168.0.19
    # scan_interval: 1
    # sensors:
      # - battery_voltage
      # - light
      # - motion
    # switches:
      # - exposure_lock
      # - ffc
      # - focus
      # - gps_active
      # - night_vision
      # - overlay
      # - torch
      # - whitebalance_lock 
      # - video_recording

arlo:
  username: !secret arlo_user
  password: !secret arlo_pass

# alarm_control_panel:
  # - platform: arlo
  
camera:
  - platform: arlo
    ffmpeg_arguments: '-pred 1 -q:v 2'
  # - platform: mjpeg
    # name: Study CAM
    # mjpeg_url: http://192.168.0.13:90/videostream.cgi
    # username: !secret study_cam_user
    # password: !secret study_cam_pass
  # - platform: mjpeg
    # name: Bar Camera
    # still_image_url: http://192.168.0.24/image.jpg
    # mjpeg_url: http://192.168.0.24/video/mjpg.cgi
    # username: !secret bar_cam_user
    # password: !secret bar_cam_pass

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg
  
# IFTTT
ifttt:
  key: !secret ifttt_key

# device_tracker:
  # - platform: owntracks_http
  
    
#WOL
wake_on_lan:

#DYSON
dyson:
  username: !secret dyson_user
  password: !secret dyson_pass
  language: AU
  devices:
    - device_id: PT7-AU-HKA3629A
      device_ip: 192.168.87.127

 
# JOIN


sensor: !include_dir_merge_list sensors    
# scene: !include scenes.yaml       
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include_dir_merge_list switches
input_boolean: !include input_boolean.yaml
shell_command: !include shell_command.yaml
binary_sensor: !include binary_sensor.yaml
history_graph: !include history_graphs.yaml
